enum ChatActionTypes {
    CHAT_SET_CONNECTED = 'CHAT_SET_CONNECTED',
    CHAT_SET_DISCONNECTED = 'CHAT_SET_DISCONNECTED',
    CHAT_SET_ERROR = 'CHAT_SET_ERROR',
    CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED',
    CHAT_SET_ROOM = 'CHAT_SET_ROOM',
};
export default ChatActionTypes;